# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-21 10:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chunks', '0002_auto__add_field_chunk_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='chunk',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=b'uploads', verbose_name='File or image'),
        ),
    ]
